### ISSUE TITLE
リクエストパラメータの必須、任意はカラムとして独立させたい

### ISSUE THREAD

**Issue by tamoryo37** [ROBOTPAYMENT/billing-robo-apispec#2]
参考
https://keirinomikata.zendesk.com/hc/ja/article_attachments/360000602761/____________10_.pdf

**Comment by mkohei** [comment]
`※更新時、「請求先部署番号」または「請求先部署コード」何れかを必須`

こういうパターンをどこに置くかですね
任意で、説明に置くのが良さそうですが
